// Global site constants — ported from PHP includes/head.php + constants/staff.php
export const SITE = {
  name: "The Oaks Plastic Surgery",
  shortName: "TOPS",
  url: "https://theoaksplasticsurgery.com",
  phone: "832-900-7070",
  phoneTel: "+18329007070",
  textNumber: "832-720-3313",
  address: {
    street: "2571 Kirby Dr",
    city: "Houston",
    state: "TX",
    zip: "77019",
    country: "US",
    lat: 29.742658,
    lng: -95.417803,
    mapsUrl: "https://goo.gl/maps/ooj1Jg2mtHXSkAyr9",
  },
  social: {
    facebook: "https://www.facebook.com/TheOaksPlasticSurgery/",
    instagram: "https://www.instagram.com/theoaksplasticsurgery/",
    youtube: "https://www.youtube.com/channel/UCIm05BvdpV9AsxgsxqoUHvw",
    linkedin: "https://www.linkedin.com/company/the-oaks-plastic-surgery/",
  },
  analytics: {
    ga: "UA-123168195-1",
    gtm: "GTM-MH39RJXG",
    facebookPixel1: "653093525077326",
    facebookPixel2: "1505009299599782",
  },
} as const;

// "Interested in" labels per page — used in consultation form overlay
// Keys are the new clean URLs (without .php)
export const INTERESTED_IN: Record<string, string> = {
  "/male-tummy-tuck-houston": "Interested in Tummy Tuck",
  "/houston-facelift": "Interested in Face lift",
  "/houston-necklift": "Interested in Neck lift",
  "/blepharoplasty-surgery-houston": "Interested in Eyelid lift",
  "/houston-eyebrow-lift": "Interested in Eyebrow lift",
  "/ear-pinning-houston": "Interested in Ear Pinning",
  "/chin-augmentation-houston": "Interested in Chin Augmentation",
  "/cheek-augmentation-houston": "Interested in Cheek Augmentation",
  "/houston-nose-jobs": "Interested in Nose Job",
  "/facial-fat-grafting-houston": "Interested in Fat Grafting",
  "/buccal-fat-removal": "Interested in Buccal Fat Removal",
  "/hair-restoration-houston": "Interested in Hair Restoration",
  "/lip-lift-houston": "Interested in Lip lift",
  "/breast-surgery-houston": "Interested in Breast Surgery",
  "/breast-implants-houston": "Interested in Breast Implants",
  "/mommy-makeover-houston": "Interested in Mommy Makeover",
  "/breast-augmentation-houston": "Interested in Breast Augmentation",
  "/breast-lift-surgery-houston": "Interested in Breast lift",
  "/breast-reduction-houston": "Interested in Breast Reduction",
  "/gynecomastia-houston": "Interested in Male Breast Reduction",
  "/breast-reconstruction-houston": "Interested in Breast Reconstruction",
  "/breast-implant-removal": "Interested in Breast Implant Removal",
  "/inverted-nipple-houston": "Interested in Inverted Nipple Repair",
  "/nipple-reduction-houston": "Interested in Nipple Reduction",
  "/butt-lift-houston": "Interested in Brazilian Butt lift",
  "/labiaplasty-houston": "Interested in Labiaplasty",
  "/houston-vaginoplasty": "Interested in Vaginal Rejuvenation",
  "/liposuction-houston": "Interested in Liposuction Surgery",
  "/arm-lift-houston": "Interested in Arm lift",
  "/lipectomy-houston": "Interested in Lower Body lift",
  "/thigh-lift-houston": "Interested in Thigh lift",
  "/houston-botox": "Interested in Botox and Dysport",
  "/fillers-houston": "Interested in Fillers",
  "/chemical-peel-houston": "Interested in Chemical Peel",
  "/vampire-facial-houston": "Interested in Vampire",
  "/microneedling-houston": "Interested in Microneedling",
  "/microdermabrasion-houston": "Interested in Microdermabrasion",
  "/kybella-houston": "Interested in Kybella",
  "/houston-skin-care-clinic": "Interested in Skin Care",
  "/reconstructive-lumpectomy-surgery-houston": "Interested in Reconstruction of Lumpectomy",
  "/migraine-treatment-houston": "Interested in Surgical Migraine Treatment",
  "/carpal-tunnel-surgery-houston": "Interested in Carpal Tunnel",
  "/cubital-tunnel-surgery-houston": "Interested in Cubital Tunnel",
  "/trigger-finger-release-surgery-houston": "Interested in Trigger Finger Surgery",
  "/dupuytrens-disease-surgery-houston": "Interested in Dupuytren's Disease Surgery",
  "/facial-skin-cancer-reconstruction-houston": "Interested in Facial Cancer Reconstruction",
  "/mass-excision-houston": "Interested in Mass Excision",
  "/massive-weight-loss-surgery": "Interested in Massive Weight Loss Surgery",
  "/scar-revision-houston-tx": "Interested in Scar Revision",
  "/c-section-closure-surgery-houston": "Interested in C Section Plastic Surgery",
  "/male-facelift-houston": "Interested in Male Facelift",
  "/houston-tummy-tucks": "Interested in Tummy Tuck",
  "/pec-implants-houston": "Interested in Pec Implants",
};
